### ISSUE TITLE
Undefined property: App\Models\.... on line 101 in ...\lluminate\Database\Eloquent\Relations\BelongsTo.php

### ISSUE THREAD

**Issue by c-myers1** [digitaldreams/laracrud#35]
With the command

    php artisan laracrud:controller Issuance --api

I'm getting the error:

    Undefined property: App\Models\Issuance::$weeklynetorderid on line 101 in C:\xampp2\htdocs\myapp\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsTo.php

weeklynetorderid is the foreign key pointing to an id column in another table. The function within the Issuance model is

    public function weeklynetorderid()
    {
        return $this->belongsTo(WeeklyNetorder::class,'weeklynetorderid');
    }

I generated WeeklyNetorder model already which is being referred to.

My searches for this error seems to indicate when there is confusion between weeklynetorderid as a function or as a property but it hasn't made a solution clearer to me.

How can I troubleshoot?

**Comment by c-myers1** [comment]
Ok, seems to be a Laravel issue as per [this](https://github.com/laravel/framework/issues/31098).

**Comment by digitaldreams** [comment]
Hi @c-myers1 
Its not a laravel issue. Let me explain what was wrong on your above code. 
You can't your belongsTo method name same as your foreign key name. 
Here your belongsTo method name `weeklynetorderid` and foreign key `weeklynetorderid` which is same name.

Rename your belongsTo method name `weeklynetorder` instead of `weeklynetorderid ` will solve your problem.
